const css= [
    {id: 1, que: "What does CSS stand for?", opt_1: "Cascading Style Sheets", opt_2: "Creative Style System", opt_3: "Computer Style Sheets", opt_4: "Colorful Style System", ans: "Cascading Style Sheets"},
    {id: 2, que: "Which property is used to change the background color in CSS?", opt_1: "color", opt_2: "background-color", opt_3: "bgcolor", opt_4: "background", ans: "background-color"},
    {id: 3, que: "What does the 'z-index' property in CSS control?", opt_1: "Element opacity", opt_2: "Stacking order", opt_3: "Position", opt_4: "Height", ans: "Stacking order"},
    {id: 4, que: "Which CSS property is used to change the font of an element?", opt_1: "font-family", opt_2: "font-style", opt_3: "font-weight", opt_4: "font", ans: "font-family"},
    {id: 5, que: "What is the default position of an HTML element?", opt_1: "static", opt_2: "relative", opt_3: "absolute", opt_4: "fixed", ans: "static"},
    {id: 6, que: "Which property is used to add spacing inside the element border?", opt_1: "margin", opt_2: "padding", opt_3: "border-spacing", opt_4: "spacing", ans: "padding"},
    {id: 7, que: "How can you make a list appear without bullet points?", opt_1: "list-style-type: none;", opt_2: "list-style: no-bullets;", opt_3: "bullet: none;", opt_4: "list: none;", ans: "list-style-type: none;"},
    {id: 8, que: "Which CSS property controls text size?", opt_1: "font-style", opt_2: "text-size", opt_3: "font-size", opt_4: "text-style", ans: "font-size"},
    {id: 9, que: "Which property is used to change the alignment of text?", opt_1: "align", opt_2: "text-align", opt_3: "horizontal-align", opt_4: "text-position", ans: "text-align"},
    {id: 10, que: "What value of 'position' will make an element stay in the same place when the page is scrolled?", opt_1: "static", opt_2: "relative", opt_3: "absolute", opt_4: "fixed", ans: "fixed"},
    {id: 11, que: "What does the 'opacity' property in CSS do?", opt_1: "Controls the color of an element", opt_2: "Changes the transparency of an element", opt_3: "Sets the element's size", opt_4: "Defines the border style", ans: "Changes the transparency of an element"},
    {id: 12, que: "Which property is used to create space between HTML elements?", opt_1: "spacing", opt_2: "padding", opt_3: "margin", opt_4: "border", ans: "margin"},
    {id: 13, que: "Which CSS property is used to change the cursor's appearance?", opt_1: "cursor-style", opt_2: "cursor", opt_3: "pointer", opt_4: "hover", ans: "cursor"},
    {id: 14, que: "What is the correct way to apply a style to a single element using an id?", opt_1: ".idname", opt_2: "#idname", opt_3: "idname", opt_4: "*idname", ans: "#idname"},
    {id: 15, que: "Which property is used to create rounded corners in CSS?", opt_1: "corner-radius", opt_2: "border-radius", opt_3: "radius", opt_4: "border-round", ans: "border-radius"},
    {id: 16, que: "How do you make an image responsive in CSS?", opt_1: "Set width: auto;", opt_2: "Set max-width: 100%;", opt_3: "Set height: auto;", opt_4: "Set margin: auto;", ans: "Set max-width: 100%;"},
    {id: 17, que: "Which property is used to control the overflow of content?", opt_1: "clip", opt_2: "overflow", opt_3: "display", opt_4: "visibility", ans: "overflow"},
    {id: 18, que: "What is the correct syntax for a CSS comment?", opt_1: "// comment", opt_2: "<!-- comment -->", opt_3: "/* comment */", opt_4: "## comment ##", ans: "/* comment */"},
    {id: 19, que: "Which CSS property is used to change the display of an element?", opt_1: "visibility", opt_2: "display", opt_3: "block", opt_4: "hidden", ans: "display"},
    {id: 20, que: "Which property controls the space between lines of text?", opt_1: "line-spacing", opt_2: "spacing", opt_3: "line-height", opt_4: "text-spacing", ans: "line-height"},
    {id: 21, que: "How do you select elements with a specific class in CSS?", opt_1: ".classname", opt_2: "#classname", opt_3: "classname", opt_4: "*classname", ans: ".classname"},
    {id: 22, que: "Which property is used to set the color of text in CSS?", opt_1: "background-color", opt_2: "text-color", opt_3: "font-color", opt_4: "color", ans: "color"},
    {id: 23, que: "What is the default display value for a div element?", opt_1: "inline", opt_2: "block", opt_3: "inline-block", opt_4: "none", ans: "block"},
    {id: 24, que: "Which value of 'position' allows elements to overlap?", opt_1: "relative", opt_2: "absolute", opt_3: "static", opt_4: "fixed", ans: "absolute"},
    {id: 25, que: "What is the 'hover' pseudo-class used for?", opt_1: "To style an element on click", opt_2: "To style an element when hovered over", opt_3: "To style a parent element", opt_4: "To style an element on load", ans: "To style an element when hovered over"},
    {id: 26, que: "Which CSS property is used to create shadows on text?", opt_1: "box-shadow", opt_2: "text-shadow", opt_3: "shadow", opt_4: "font-shadow", ans: "text-shadow"},
    {id: 27, que: "How do you apply styles to all <p> elements inside a <div>?", opt_1: "div p", opt_2: "div > p", opt_3: "div + p", opt_4: "div ~ p", ans: "div p"},
    {id: 28, que: "Which property is used to define the width of a border?", opt_1: "border-style", opt_2: "border-width", opt_3: "border-color", opt_4: "border", ans: "border-width"},
    {id: 29, que: "What does the 'max-width' property do?", opt_1: "Sets the maximum height of an element", opt_2: "Sets the maximum width of an element", opt_3: "Sets both width and height", opt_4: "Sets the padding size", ans: "Sets the maximum width of an element"},
    {id: 30, que: "Which property specifies whether the element's box should float?", opt_1: "display", opt_2: "float", opt_3: "align", opt_4: "position", ans: "float"},
    {id: 31, que: "Which CSS property defines the space between border and content?", opt_1: "margin", opt_2: "padding", opt_3: "border-spacing", opt_4: "spacing", ans: "padding"},
    {id: 32, que: "How can you specify multiple background images?", opt_1: "background-multiple", opt_2: "background-list", opt_3: "background", opt_4: "background-image", ans: "background-image"},
    {id: 33, que: "Which property is used to make text bold?", opt_1: "font-weight", opt_2: "font-style", opt_3: "text-bold", opt_4: "font", ans: "font-weight"},
    {id: 34, que: "Which property changes the style of a border?", opt_1: "border-style", opt_2: "border-weight", opt_3: "border-color", opt_4: "border-radius", ans: "border-style"},
    {id: 35, que: "What does the 'clip-path' property do?", opt_1: "Clips the image edges", opt_2: "Defines a visible path for the element", opt_3: "Hides the element", opt_4: "Resizes the element", ans: "Defines a visible path for the element"},
    {id: 36, que: "Which property controls the flexibility of a flex item?", opt_1: "flex-grow", opt_2: "flex-basis", opt_3: "flex-wrap", opt_4: "flex-flow", ans: "flex-grow"},
    {id: 37, que: "How do you align items along the cross-axis in Flexbox?", opt_1: "justify-content", opt_2: "align-items", opt_3: "flex-align", opt_4: "align-content", ans: "align-items"},
    {id: 38, que: "What is the function of the 'transition' property in CSS?", opt_1: "Changes element background", opt_2: "Animates properties over a duration", opt_3: "Sets the element position", opt_4: "Defines element size", ans: "Animates properties over a duration"},
    {id: 39, que: "What does the 'grid-template-columns' property define in CSS Grid?", opt_1: "Number of rows in the grid", opt_2: "Number of columns in the grid", opt_3: "Column sizes and gaps", opt_4: "Alignment of columns", ans: "Number of columns in the grid"},
    {id: 40, que: "Which value of the 'display' property is used for grid layouts?", opt_1: "inline", opt_2: "flex", opt_3: "grid", opt_4: "block", ans: "grid"},
    {id: 41, que: "What is the shorthand property for margin?", opt_1: "margin-all", opt_2: "margin", opt_3: "spacing", opt_4: "margin-inline", ans: "margin"},
    {id: 42, que: "Which property is used to create a shadow effect for elements?", opt_1: "box-shadow", opt_2: "element-shadow", opt_3: "shadow", opt_4: "outline", ans: "box-shadow"},
    {id: 43, que: "Which pseudo-element is used to style the first letter of a text?", opt_1: "::letter", opt_2: "::first", opt_3: "::first-letter", opt_4: "::text", ans: "::first-letter"},
    {id: 44, que: "What does 'media query' allow in CSS?", opt_1: "Creates animations", opt_2: "Applies styles based on device width", opt_3: "Resets CSS styles", opt_4: "Defines global variables", ans: "Applies styles based on device width"},
    {id: 45, que: "Which CSS function is used to apply a gradient background?", opt_1: "linear-gradient()", opt_2: "background-gradient()", opt_3: "gradient()", opt_4: "gradient-fill()", ans: "linear-gradient()"},
    {id: 46, que: "What does the 'visibility' property do in CSS?", opt_1: "Hides an element", opt_2: "Removes the element from the DOM", opt_3: "Makes the element background transparent", opt_4: "Changes the z-index of the element", ans: "Hides an element"},
    {id: 47, que: "Which property is used to specify the distance between words?", opt_1: "letter-spacing", opt_2: "word-spacing", opt_3: "text-spacing", opt_4: "spacing", ans: "word-spacing"},
    {id: 48, que: "Which CSS property is used to apply 3D transformations?", opt_1: "transform-3D", opt_2: "transform", opt_3: "perspective", opt_4: "animation", ans: "transform"},
    {id: 49, que: "How can you hide an element but keep its space in the layout?", opt_1: "display: none;", opt_2: "visibility: hidden;", opt_3: "opacity: 0;", opt_4: "position: hidden;", ans: "visibility: hidden;"},
    {id: 50, que: "What is the difference between 'em' and 'rem' units in CSS?", opt_1: "'em' is relative to the root element, 'rem' is relative to the parent", opt_2: "'rem' is relative to the root element, 'em' is relative to the parent", opt_3: "Both are absolute units", opt_4: "No difference", ans: "'rem' is relative to the root element, 'em' is relative to the parent"}
    ];
    
