const html=[
    {id: 1, que: "What does HTML stand for?", opt_1: "Hyper Text Markup Language", opt_2: "Hyperlinks and Text Markup Language", opt_3: "Home Tool Markup Language", opt_4: "Hyper Tool Markup Language", ans: "Hyper Text Markup Language"},
    {id: 2, que: "Which HTML element is used to define the largest heading?", opt_1: "<h1>", opt_2: "<heading>", opt_3: "<h6>", opt_4: "<head>", ans: "<h1>"},
    {id: 3, que: "Which tag is used to create a hyperlink in HTML?", opt_1: "<a>", opt_2: "<link>", opt_3: "<href>", opt_4: "<url>", ans: "<a>"},
    {id: 4, que: "Which HTML element is used to insert an image?", opt_1: "<img>", opt_2: "<picture>", opt_3: "<image>", opt_4: "<src>", ans: "<img>"},
    {id: 5, que: "What is the purpose of the <title> tag?", opt_1: "To set the title of the web page", opt_2: "To define headings", opt_3: "To create hyperlinks", opt_4: "To include metadata", ans: "To set the title of the web page"},
    {id: 6, que: "Which attribute is used to provide alternative text for an image?", opt_1: "alt", opt_2: "src", opt_3: "title", opt_4: "description", ans: "alt"},
    {id: 7, que: "Which tag is used to create an ordered list?", opt_1: "<ol>", opt_2: "<ul>", opt_3: "<li>", opt_4: "<list>", ans: "<ol>"},
    {id: 8, que: "Which tag is used to create a table row?", opt_1: "<tr>", opt_2: "<td>", opt_3: "<th>", opt_4: "<row>", ans: "<tr>"},
    {id: 9, que: "What does the <br> tag do?", opt_1: "Inserts a line break", opt_2: "Creates bold text", opt_3: "Creates a border", opt_4: "Inserts a paragraph", ans: "Inserts a line break"},
    {id: 10, que: "Which attribute specifies the URL of a link?", opt_1: "href", opt_2: "src", opt_3: "alt", opt_4: "link", ans: "href"},
    {id: 11, que: "Which HTML tag is used to define metadata about a document?", opt_1: "<meta>", opt_2: "<head>", opt_3: "<title>", opt_4: "<link>", ans: "<meta>"},
    {id: 12, que: "Which HTML attribute is used to define inline styles?", opt_1: "style", opt_2: "class", opt_3: "id", opt_4: "css", ans: "style"},
    {id: 13, que: "What is the purpose of the <form> tag?", opt_1: "To collect user input", opt_2: "To format text", opt_3: "To insert images", opt_4: "To create links", ans: "To collect user input"},
    {id: 14, que: "Which tag is used to create a checkbox in HTML?", opt_1: "<input type='checkbox'>", opt_2: "<checkbox>", opt_3: "<input type='box'>", opt_4: "<check>", ans: "<input type='checkbox'>"},
    {id: 15, que: "Which HTML element is used to define a footer for a document?", opt_1: "<footer>", opt_2: "<foot>", opt_3: "<bottom>", opt_4: "<section>", ans: "<footer>"},
    {id: 16, que: "Which tag is used to create a dropdown list?", opt_1: "<select>", opt_2: "<dropdown>", opt_3: "<list>", opt_4: "<option>", ans: "<select>"},
    {id: 17, que: "Which HTML element is used to play audio files?", opt_1: "<audio>", opt_2: "<sound>", opt_3: "<play>", opt_4: "<media>", ans: "<audio>"},
    {id: 18, que: "Which tag is used to create a horizontal line?", opt_1: "<hr>", opt_2: "<line>", opt_3: "<br>", opt_4: "<divider>", ans: "<hr>"},
    {id: 19, que: "What does the <head> tag contain?", opt_1: "Metadata and links to scripts or styles", opt_2: "The main content", opt_3: "Page footer", opt_4: "Navigation links", ans: "Metadata and links to scripts or styles"},
    {id: 20, que: "Which attribute is used to specify a unique identifier for an element?", opt_1: "id", opt_2: "class", opt_3: "style", opt_4: "name", ans: "id"},
    {id: 21, que: "Which tag is used to define emphasized text?", opt_1: "<em>", opt_2: "<i>", opt_3: "<b>", opt_4: "<strong>", ans: "<em>"},
    {id: 22, que: "Which HTML tag is used to create a division or a section?", opt_1: "<div>", opt_2: "<section>", opt_3: "<article>", opt_4: "<span>", ans: "<div>"},
    {id: 23, que: "Which tag is used to create a clickable button?", opt_1: "<button>", opt_2: "<input>", opt_3: "<click>", opt_4: "<action>", ans: "<button>"},
    {id: 24, que: "Which element is used for creating multi-line text input?", opt_1: "<textarea>", opt_2: "<input>", opt_3: "<multiline>", opt_4: "<text>", ans: "<textarea>"},
    {id: 25, que: "Which attribute specifies the maximum length of input in a text field?", opt_1: "maxlength", opt_2: "maxinput", opt_3: "length", opt_4: "maxlen", ans: "maxlength"},
    {id: 26, que: "What is the purpose of the <nav> tag?", opt_1: "Defines navigation links", opt_2: "Creates a table", opt_3: "Adds a footer", opt_4: "Adds an image", ans: "Defines navigation links"},
    {id: 27, que: "Which tag is used for inserting a video?", opt_1: "<video>", opt_2: "<media>", opt_3: "<play>", opt_4: "<movie>", ans: "<video>"},
    {id: 28, que: "Which attribute is used to set the language of an HTML document?", opt_1: "lang", opt_2: "language", opt_3: "locale", opt_4: "code", ans: "lang"},
    {id: 29, que: "Which tag is used to group inline elements in HTML?", opt_1: "<span>", opt_2: "<div>", opt_3: "<section>", opt_4: "<group>", ans: "<span>"},
    {id: 30, que: "What is the correct doctype for an HTML5 document?", opt_1: "<!DOCTYPE html>", opt_2: "<!DOCTYPE HTML5>", opt_3: "<DOCTYPE html5>", opt_4: "<DOCTYPE HTML>", ans: "<!DOCTYPE html>"},
    {id: 31, que: "Which attribute specifies the width of a table?", opt_1: "width", opt_2: "table-width", opt_3: "size", opt_4: "length", ans: "width"},
    {id: 32, que: "Which tag is used to define a caption for a table?", opt_1: "<caption>", opt_2: "<table-caption>", opt_3: "<summary>", opt_4: "<header>", ans: "<caption>"},
    {id: 33, que: "Which element is used to create a progress bar?", opt_1: "<progress>", opt_2: "<bar>", opt_3: "<meter>", opt_4: "<range>", ans: "<progress>"},
    {id: 34, que: "Which tag is used to define a definition list?", opt_1: "<dl>", opt_2: "<dd>", opt_3: "<dt>", opt_4: "<list>", ans: "<dl>"},
    {id: 35, que: "Which tag is used to embed an external application?", opt_1: "<embed>", opt_2: "<app>", opt_3: "<iframe>", opt_4: "<object>", ans: "<embed>"},
    {id: 36, que: "Which tag is used to embed an external application?", opt_1: "<embed>", opt_2: "<app>", opt_3: "<iframe>", opt_4: "<object>", ans: "<embed>"},
    {id: 37, que: "Which HTML element represents the main content of the document?", opt_1: "<main>", opt_2: "<body>", opt_3: "<section>", opt_4: "<article>", ans: "<main>"},
    {id: 38, que: "Which attribute specifies that an input field is mandatory?", opt_1: "required", opt_2: "mandatory", opt_3: "needed", opt_4: "validate", ans: "required"},
    {id: 39, que: "Which tag is used to define preformatted text?", opt_1: "<pre>", opt_2: "<code>", opt_3: "<format>", opt_4: "<text>", ans: "<pre>"},
    {id: 40, que: "What is the purpose of the <strong> tag?", opt_1: "To indicate strong importance", opt_2: "To italicize text", opt_3: "To underline text", opt_4: "To create headings", ans: "To indicate strong importance"},
    {id: 41, que: "Which tag is used to create a line-through effect on text?", opt_1: "<s>", opt_2: "<strike>", opt_3: "<del>", opt_4: "<line>", ans: "<s>"},
    {id: 42, que: "Which element is used to define a container for content that is hidden until required?", opt_1: "<details>", opt_2: "<summary>", opt_3: "<aside>", opt_4: "<dialog>", ans: "<details>"},
    {id: 43, que: "Which tag is used to define a label for an input element?", opt_1: "<label>", opt_2: "<input>", opt_3: "<caption>", opt_4: "<title>", ans: "<label>"},
    {id: 44, que: "What does the <abbr> tag define?", opt_1: "An abbreviation", opt_2: "A hyperlink", opt_3: "A blockquote", opt_4: "A bold text", ans: "An abbreviation"},
    {id: 45, que: "Which attribute specifies the character encoding for an HTML document?", opt_1: "charset", opt_2: "encoding", opt_3: "lang", opt_4: "type", ans: "charset"},
    {id: 46, que: "What is the purpose of the <mark> tag?", opt_1: "To highlight text", opt_2: "To underline text", opt_3: "To bold text", opt_4: "To italicize text", ans: "To highlight text"},
    {id: 47, que: "Which tag is used to define a section in a document?", opt_1: "<section>", opt_2: "<article>", opt_3: "<div>", opt_4: "<aside>", ans: "<section>"},
    {id: 48, que: "Which element is used to define a scalar measurement within a range?", opt_1: "<meter>", opt_2: "<range>", opt_3: "<progress>", opt_4: "<value>", ans: "<meter>"},
    {id: 49, que: "Which attribute is used to merge cells in a table horizontally?", opt_1: "colspan", opt_2: "rowspan", opt_3: "merge", opt_4: "span", ans: "colspan"},
    {id: 50, que: "What is the purpose of the <time> tag?", opt_1: "To represent a specific time or duration", opt_2: "To display the current time", opt_3: "To format time", opt_4: "To create a clock", ans: "To represent a specific time or duration"}
];

