const questions={
html:[
    {id: 1, que: "What does HTML stand for?", opt_1: "Hyper Text Markup Language", opt_2: "Hyperlinks and Text Markup Language", opt_3: "Home Tool Markup Language", opt_4: "Hyper Tool Markup Language", ans: "Hyper Text Markup Language"},
    {id: 2, que: "Which HTML element is used to define the largest heading?", opt_1: "<h1>", opt_2: "<heading>", opt_3: "<h6>", opt_4: "<head>", ans: "<h1>"},
    {id: 3, que: "Which tag is used to create a hyperlink in HTML?", opt_1: "<a>", opt_2: "<link>", opt_3: "<href>", opt_4: "<url>", ans: "<a>"},
    {id: 4, que: "Which HTML element is used to insert an image?", opt_1: "<img>", opt_2: "<picture>", opt_3: "<image>", opt_4: "<src>", ans: "<img>"},
    {id: 5, que: "What is the purpose of the <title> tag?", opt_1: "To set the title of the web page", opt_2: "To define headings", opt_3: "To create hyperlinks", opt_4: "To include metadata", ans: "To set the title of the web page"},
    {id: 6, que: "Which attribute is used to provide alternative text for an image?", opt_1: "alt", opt_2: "src", opt_3: "title", opt_4: "description", ans: "alt"},
    {id: 7, que: "Which tag is used to create an ordered list?", opt_1: "<ol>", opt_2: "<ul>", opt_3: "<li>", opt_4: "<list>", ans: "<ol>"},
    {id: 8, que: "Which tag is used to create a table row?", opt_1: "<tr>", opt_2: "<td>", opt_3: "<th>", opt_4: "<row>", ans: "<tr>"},
    {id: 9, que: "What does the <br> tag do?", opt_1: "Inserts a line break", opt_2: "Creates bold text", opt_3: "Creates a border", opt_4: "Inserts a paragraph", ans: "Inserts a line break"},
    {id: 10, que: "Which attribute specifies the URL of a link?", opt_1: "href", opt_2: "src", opt_3: "alt", opt_4: "link", ans: "href"},
    {id: 11, que: "Which HTML tag is used to define metadata about a document?", opt_1: "<meta>", opt_2: "<head>", opt_3: "<title>", opt_4: "<link>", ans: "<meta>"},
    {id: 12, que: "Which HTML attribute is used to define inline styles?", opt_1: "style", opt_2: "class", opt_3: "id", opt_4: "css", ans: "style"},
    {id: 13, que: "What is the purpose of the <form> tag?", opt_1: "To collect user input", opt_2: "To format text", opt_3: "To insert images", opt_4: "To create links", ans: "To collect user input"},
    {id: 14, que: "Which tag is used to create a checkbox in HTML?", opt_1: "<input type='checkbox'>", opt_2: "<checkbox>", opt_3: "<input type='box'>", opt_4: "<check>", ans: "<input type='checkbox'>"},
    {id: 15, que: "Which HTML element is used to define a footer for a document?", opt_1: "<footer>", opt_2: "<foot>", opt_3: "<bottom>", opt_4: "<section>", ans: "<footer>"},
    {id: 16, que: "Which tag is used to create a dropdown list?", opt_1: "<select>", opt_2: "<dropdown>", opt_3: "<list>", opt_4: "<option>", ans: "<select>"},
    {id: 17, que: "Which HTML element is used to play audio files?", opt_1: "<audio>", opt_2: "<sound>", opt_3: "<play>", opt_4: "<media>", ans: "<audio>"},
    {id: 18, que: "Which tag is used to create a horizontal line?", opt_1: "<hr>", opt_2: "<line>", opt_3: "<br>", opt_4: "<divider>", ans: "<hr>"},
    {id: 19, que: "What does the <head> tag contain?", opt_1: "Metadata and links to scripts or styles", opt_2: "The main content", opt_3: "Page footer", opt_4: "Navigation links", ans: "Metadata and links to scripts or styles"},
    {id: 20, que: "Which attribute is used to specify a unique identifier for an element?", opt_1: "id", opt_2: "class", opt_3: "style", opt_4: "name", ans: "id"},
    {id: 21, que: "Which tag is used to define emphasized text?", opt_1: "<em>", opt_2: "<i>", opt_3: "<b>", opt_4: "<strong>", ans: "<em>"},
    {id: 22, que: "Which HTML tag is used to create a division or a section?", opt_1: "<div>", opt_2: "<section>", opt_3: "<article>", opt_4: "<span>", ans: "<div>"},
    {id: 23, que: "Which tag is used to create a clickable button?", opt_1: "<button>", opt_2: "<input>", opt_3: "<click>", opt_4: "<action>", ans: "<button>"},
    {id: 24, que: "Which element is used for creating multi-line text input?", opt_1: "<textarea>", opt_2: "<input>", opt_3: "<multiline>", opt_4: "<text>", ans: "<textarea>"},
    {id: 25, que: "Which attribute specifies the maximum length of input in a text field?", opt_1: "maxlength", opt_2: "maxinput", opt_3: "length", opt_4: "maxlen", ans: "maxlength"},
    {id: 26, que: "What is the purpose of the <nav> tag?", opt_1: "Defines navigation links", opt_2: "Creates a table", opt_3: "Adds a footer", opt_4: "Adds an image", ans: "Defines navigation links"},
    {id: 27, que: "Which tag is used for inserting a video?", opt_1: "<video>", opt_2: "<media>", opt_3: "<play>", opt_4: "<movie>", ans: "<video>"},
    {id: 28, que: "Which attribute is used to set the language of an HTML document?", opt_1: "lang", opt_2: "language", opt_3: "locale", opt_4: "code", ans: "lang"},
    {id: 29, que: "Which tag is used to group inline elements in HTML?", opt_1: "<span>", opt_2: "<div>", opt_3: "<section>", opt_4: "<group>", ans: "<span>"},
    {id: 30, que: "What is the correct doctype for an HTML5 document?", opt_1: "<!DOCTYPE html>", opt_2: "<!DOCTYPE HTML5>", opt_3: "<DOCTYPE html5>", opt_4: "<DOCTYPE HTML>", ans: "<!DOCTYPE html>"},
    {id: 31, que: "Which attribute specifies the width of a table?", opt_1: "width", opt_2: "table-width", opt_3: "size", opt_4: "length", ans: "width"},
    {id: 32, que: "Which tag is used to define a caption for a table?", opt_1: "<caption>", opt_2: "<table-caption>", opt_3: "<summary>", opt_4: "<header>", ans: "<caption>"},
    {id: 33, que: "Which element is used to create a progress bar?", opt_1: "<progress>", opt_2: "<bar>", opt_3: "<meter>", opt_4: "<range>", ans: "<progress>"},
    {id: 34, que: "Which tag is used to define a definition list?", opt_1: "<dl>", opt_2: "<dd>", opt_3: "<dt>", opt_4: "<list>", ans: "<dl>"},
    {id: 35, que: "Which tag is used to embed an external application?", opt_1: "<embed>", opt_2: "<app>", opt_3: "<iframe>", opt_4: "<object>", ans: "<embed>"},
    {id: 36, que: "Which tag is used to embed an external application?", opt_1: "<embed>", opt_2: "<app>", opt_3: "<iframe>", opt_4: "<object>", ans: "<embed>"},
    {id: 37, que: "Which HTML element represents the main content of the document?", opt_1: "<main>", opt_2: "<body>", opt_3: "<section>", opt_4: "<article>", ans: "<main>"},
    {id: 38, que: "Which attribute specifies that an input field is mandatory?", opt_1: "required", opt_2: "mandatory", opt_3: "needed", opt_4: "validate", ans: "required"},
    {id: 39, que: "Which tag is used to define preformatted text?", opt_1: "<pre>", opt_2: "<code>", opt_3: "<format>", opt_4: "<text>", ans: "<pre>"},
    {id: 40, que: "What is the purpose of the <strong> tag?", opt_1: "To indicate strong importance", opt_2: "To italicize text", opt_3: "To underline text", opt_4: "To create headings", ans: "To indicate strong importance"},
    {id: 41, que: "Which tag is used to create a line-through effect on text?", opt_1: "<s>", opt_2: "<strike>", opt_3: "<del>", opt_4: "<line>", ans: "<s>"},
    {id: 42, que: "Which element is used to define a container for content that is hidden until required?", opt_1: "<details>", opt_2: "<summary>", opt_3: "<aside>", opt_4: "<dialog>", ans: "<details>"},
    {id: 43, que: "Which tag is used to define a label for an input element?", opt_1: "<label>", opt_2: "<input>", opt_3: "<caption>", opt_4: "<title>", ans: "<label>"},
    {id: 44, que: "What does the <abbr> tag define?", opt_1: "An abbreviation", opt_2: "A hyperlink", opt_3: "A blockquote", opt_4: "A bold text", ans: "An abbreviation"},
    {id: 45, que: "Which attribute specifies the character encoding for an HTML document?", opt_1: "charset", opt_2: "encoding", opt_3: "lang", opt_4: "type", ans: "charset"},
    {id: 46, que: "What is the purpose of the <mark> tag?", opt_1: "To highlight text", opt_2: "To underline text", opt_3: "To bold text", opt_4: "To italicize text", ans: "To highlight text"},
    {id: 47, que: "Which tag is used to define a section in a document?", opt_1: "<section>", opt_2: "<article>", opt_3: "<div>", opt_4: "<aside>", ans: "<section>"},
    {id: 48, que: "Which element is used to define a scalar measurement within a range?", opt_1: "<meter>", opt_2: "<range>", opt_3: "<progress>", opt_4: "<value>", ans: "<meter>"},
    {id: 49, que: "Which attribute is used to merge cells in a table horizontally?", opt_1: "colspan", opt_2: "rowspan", opt_3: "merge", opt_4: "span", ans: "colspan"},
    {id: 50, que: "What is the purpose of the <time> tag?", opt_1: "To represent a specific time or duration", opt_2: "To display the current time", opt_3: "To format time", opt_4: "To create a clock", ans: "To represent a specific time or duration"}
],
css:[
    {id: 1, que: "What does CSS stand for?", opt_1: "Cascading Style Sheets", opt_2: "Creative Style System", opt_3: "Computer Style Sheets", opt_4: "Colorful Style System", ans: "Cascading Style Sheets"},
    {id: 2, que: "Which property is used to change the background color in CSS?", opt_1: "color", opt_2: "background-color", opt_3: "bgcolor", opt_4: "background", ans: "background-color"},
    {id: 3, que: "What does the 'z-index' property in CSS control?", opt_1: "Element opacity", opt_2: "Stacking order", opt_3: "Position", opt_4: "Height", ans: "Stacking order"},
    {id: 4, que: "Which CSS property is used to change the font of an element?", opt_1: "font-family", opt_2: "font-style", opt_3: "font-weight", opt_4: "font", ans: "font-family"},
    {id: 5, que: "What is the default position of an HTML element?", opt_1: "static", opt_2: "relative", opt_3: "absolute", opt_4: "fixed", ans: "static"},
    {id: 6, que: "Which property is used to add spacing inside the element border?", opt_1: "margin", opt_2: "padding", opt_3: "border-spacing", opt_4: "spacing", ans: "padding"},
    {id: 7, que: "How can you make a list appear without bullet points?", opt_1: "list-style-type: none;", opt_2: "list-style: no-bullets;", opt_3: "bullet: none;", opt_4: "list: none;", ans: "list-style-type: none;"},
    {id: 8, que: "Which CSS property controls text size?", opt_1: "font-style", opt_2: "text-size", opt_3: "font-size", opt_4: "text-style", ans: "font-size"},
    {id: 9, que: "Which property is used to change the alignment of text?", opt_1: "align", opt_2: "text-align", opt_3: "horizontal-align", opt_4: "text-position", ans: "text-align"},
    {id: 10, que: "What value of 'position' will make an element stay in the same place when the page is scrolled?", opt_1: "static", opt_2: "relative", opt_3: "absolute", opt_4: "fixed", ans: "fixed"},
    {id: 11, que: "What does the 'opacity' property in CSS do?", opt_1: "Controls the color of an element", opt_2: "Changes the transparency of an element", opt_3: "Sets the element's size", opt_4: "Defines the border style", ans: "Changes the transparency of an element"},
    {id: 12, que: "Which property is used to create space between HTML elements?", opt_1: "spacing", opt_2: "padding", opt_3: "margin", opt_4: "border", ans: "margin"},
    {id: 13, que: "Which CSS property is used to change the cursor's appearance?", opt_1: "cursor-style", opt_2: "cursor", opt_3: "pointer", opt_4: "hover", ans: "cursor"},
    {id: 14, que: "What is the correct way to apply a style to a single element using an id?", opt_1: ".idname", opt_2: "#idname", opt_3: "idname", opt_4: "*idname", ans: "#idname"},
    {id: 15, que: "Which property is used to create rounded corners in CSS?", opt_1: "corner-radius", opt_2: "border-radius", opt_3: "radius", opt_4: "border-round", ans: "border-radius"},
    {id: 16, que: "How do you make an image responsive in CSS?", opt_1: "Set width: auto;", opt_2: "Set max-width: 100%;", opt_3: "Set height: auto;", opt_4: "Set margin: auto;", ans: "Set max-width: 100%;"},
    {id: 17, que: "Which property is used to control the overflow of content?", opt_1: "clip", opt_2: "overflow", opt_3: "display", opt_4: "visibility", ans: "overflow"},
    {id: 18, que: "What is the correct syntax for a CSS comment?", opt_1: "// comment", opt_2: "<!-- comment -->", opt_3: "/* comment */", opt_4: "## comment ##", ans: "/* comment */"},
    {id: 19, que: "Which CSS property is used to change the display of an element?", opt_1: "visibility", opt_2: "display", opt_3: "block", opt_4: "hidden", ans: "display"},
    {id: 20, que: "Which property controls the space between lines of text?", opt_1: "line-spacing", opt_2: "spacing", opt_3: "line-height", opt_4: "text-spacing", ans: "line-height"},
    {id: 21, que: "How do you select elements with a specific class in CSS?", opt_1: ".classname", opt_2: "#classname", opt_3: "classname", opt_4: "*classname", ans: ".classname"},
    {id: 22, que: "Which property is used to set the color of text in CSS?", opt_1: "background-color", opt_2: "text-color", opt_3: "font-color", opt_4: "color", ans: "color"},
    {id: 23, que: "What is the default display value for a div element?", opt_1: "inline", opt_2: "block", opt_3: "inline-block", opt_4: "none", ans: "block"},
    {id: 24, que: "Which value of 'position' allows elements to overlap?", opt_1: "relative", opt_2: "absolute", opt_3: "static", opt_4: "fixed", ans: "absolute"},
    {id: 25, que: "What is the 'hover' pseudo-class used for?", opt_1: "To style an element on click", opt_2: "To style an element when hovered over", opt_3: "To style a parent element", opt_4: "To style an element on load", ans: "To style an element when hovered over"},
    {id: 26, que: "Which CSS property is used to create shadows on text?", opt_1: "box-shadow", opt_2: "text-shadow", opt_3: "shadow", opt_4: "font-shadow", ans: "text-shadow"},
    {id: 27, que: "How do you apply styles to all <p> elements inside a <div>?", opt_1: "div p", opt_2: "div > p", opt_3: "div + p", opt_4: "div ~ p", ans: "div p"},
    {id: 28, que: "Which property is used to define the width of a border?", opt_1: "border-style", opt_2: "border-width", opt_3: "border-color", opt_4: "border", ans: "border-width"},
    {id: 29, que: "What does the 'max-width' property do?", opt_1: "Sets the maximum height of an element", opt_2: "Sets the maximum width of an element", opt_3: "Sets both width and height", opt_4: "Sets the padding size", ans: "Sets the maximum width of an element"},
    {id: 30, que: "Which property specifies whether the element's box should float?", opt_1: "display", opt_2: "float", opt_3: "align", opt_4: "position", ans: "float"},
    {id: 31, que: "Which CSS property defines the space between border and content?", opt_1: "margin", opt_2: "padding", opt_3: "border-spacing", opt_4: "spacing", ans: "padding"},
    {id: 32, que: "How can you specify multiple background images?", opt_1: "background-multiple", opt_2: "background-list", opt_3: "background", opt_4: "background-image", ans: "background-image"},
    {id: 33, que: "Which property is used to make text bold?", opt_1: "font-weight", opt_2: "font-style", opt_3: "text-bold", opt_4: "font", ans: "font-weight"},
    {id: 34, que: "Which property changes the style of a border?", opt_1: "border-style", opt_2: "border-weight", opt_3: "border-color", opt_4: "border-radius", ans: "border-style"},
    {id: 35, que: "What does the 'clip-path' property do?", opt_1: "Clips the image edges", opt_2: "Defines a visible path for the element", opt_3: "Hides the element", opt_4: "Resizes the element", ans: "Defines a visible path for the element"},
    {id: 36, que: "Which property controls the flexibility of a flex item?", opt_1: "flex-grow", opt_2: "flex-basis", opt_3: "flex-wrap", opt_4: "flex-flow", ans: "flex-grow"},
    {id: 37, que: "How do you align items along the cross-axis in Flexbox?", opt_1: "justify-content", opt_2: "align-items", opt_3: "flex-align", opt_4: "align-content", ans: "align-items"},
    {id: 38, que: "What is the function of the 'transition' property in CSS?", opt_1: "Changes element background", opt_2: "Animates properties over a duration", opt_3: "Sets the element position", opt_4: "Defines element size", ans: "Animates properties over a duration"},
    {id: 39, que: "What does the 'grid-template-columns' property define in CSS Grid?", opt_1: "Number of rows in the grid", opt_2: "Number of columns in the grid", opt_3: "Column sizes and gaps", opt_4: "Alignment of columns", ans: "Number of columns in the grid"},
    {id: 40, que: "Which value of the 'display' property is used for grid layouts?", opt_1: "inline", opt_2: "flex", opt_3: "grid", opt_4: "block", ans: "grid"},
    {id: 41, que: "What is the shorthand property for margin?", opt_1: "margin-all", opt_2: "margin", opt_3: "spacing", opt_4: "margin-inline", ans: "margin"},
    {id: 42, que: "Which property is used to create a shadow effect for elements?", opt_1: "box-shadow", opt_2: "element-shadow", opt_3: "shadow", opt_4: "outline", ans: "box-shadow"},
    {id: 43, que: "Which pseudo-element is used to style the first letter of a text?", opt_1: "::letter", opt_2: "::first", opt_3: "::first-letter", opt_4: "::text", ans: "::first-letter"},
    {id: 44, que: "What does 'media query' allow in CSS?", opt_1: "Creates animations", opt_2: "Applies styles based on device width", opt_3: "Resets CSS styles", opt_4: "Defines global variables", ans: "Applies styles based on device width"},
    {id: 45, que: "Which CSS function is used to apply a gradient background?", opt_1: "linear-gradient()", opt_2: "background-gradient()", opt_3: "gradient()", opt_4: "gradient-fill()", ans: "linear-gradient()"},
    {id: 46, que: "What does the 'visibility' property do in CSS?", opt_1: "Hides an element", opt_2: "Removes the element from the DOM", opt_3: "Makes the element background transparent", opt_4: "Changes the z-index of the element", ans: "Hides an element"},
    {id: 47, que: "Which property is used to specify the distance between words?", opt_1: "letter-spacing", opt_2: "word-spacing", opt_3: "text-spacing", opt_4: "spacing", ans: "word-spacing"},
    {id: 48, que: "Which CSS property is used to apply 3D transformations?", opt_1: "transform-3D", opt_2: "transform", opt_3: "perspective", opt_4: "animation", ans: "transform"},
    {id: 49, que: "How can you hide an element but keep its space in the layout?", opt_1: "display: none;", opt_2: "visibility: hidden;", opt_3: "opacity: 0;", opt_4: "position: hidden;", ans: "visibility: hidden;"},
    {id: 50, que: "What is the difference between 'em' and 'rem' units in CSS?", opt_1: "'em' is relative to the root element, 'rem' is relative to the parent", opt_2: "'rem' is relative to the root element, 'em' is relative to the parent", opt_3: "Both are absolute units", opt_4: "No difference", ans: "'rem' is relative to the root element, 'em' is relative to the parent"}
    ],
js:[
    {id: 1, que: "What is JavaScript primarily used for?", opt_1: "Styling web pages", opt_2: "Adding interactivity to web pages", opt_3: "Structuring web pages", opt_4: "Managing databases", ans: "Adding interactivity to web pages"},
    {id: 2, que: "Which company developed JavaScript?", opt_1: "Microsoft", opt_2: "Netscape", opt_3: "Google", opt_4: "Apple", ans: "Netscape"},
    {id: 3, que: "Which keyword is used to declare a variable in JavaScript?", opt_1: "var", opt_2: "let", opt_3: "const", opt_4: "All of the above", ans: "All of the above"},
    {id: 4, que: "What does 'DOM' stand for?", opt_1: "Document Object Model", opt_2: "Display Object Management", opt_3: "Digital Object Model", opt_4: "Document Orientation Model", ans: "Document Object Model"},
    {id: 5, que: "Which symbol is used for comments in JavaScript?", opt_1: "//", opt_2: "/* */", opt_3: "<!-- -->", opt_4: "Both // and /* */", ans: "Both // and /* */"},
    {id: 6, que: "Which method is used to find the length of a string?", opt_1: "length", opt_2: "size", opt_3: "strlen", opt_4: "count", ans: "length"},
    {id: 7, que: "How can you convert a string to an integer in JavaScript?", opt_1: "parseInt()", opt_2: "Number()", opt_3: "Both A and B", opt_4: "String()", ans: "Both A and B"},
    {id: 8, que: "Which method is used to add an element to the end of an array?", opt_1: "push()", opt_2: "pop()", opt_3: "shift()", opt_4: "unshift()", ans: "push()"},
    {id: 9, que: "What does 'NaN' represent in JavaScript?", opt_1: "Not a Number", opt_2: "Null and None", opt_3: "Negative and Null", opt_4: "None of the above", ans: "Not a Number"},
    {id: 10, que: "Which operator is used to compare both value and type?", opt_1: "===", opt_2: "==", opt_3: "=", opt_4: "!=", ans: "==="},
    {id: 11, que: "What is the correct way to create a function in JavaScript?", opt_1: "function myFunction() {}", opt_2: "def myFunction()", opt_3: "function: myFunction {}", opt_4: "fun myFunction() {}", ans: "function myFunction() {}"},
    {id: 12, que: "Which event occurs when a user clicks on an HTML element?", opt_1: "onclick", opt_2: "onchange", opt_3: "onhover", opt_4: "onmouseclick", ans: "onclick"},
    {id: 13, que: "What is the output of 'typeof null' in JavaScript?", opt_1: "object", opt_2: "null", opt_3: "undefined", opt_4: "string", ans: "object"},
    {id: 14, que: "How can you detect the client's browser name in JavaScript?", opt_1: "navigator.appName", opt_2: "browser.name", opt_3: "client.name", opt_4: "document.name", ans: "navigator.appName"},
    {id: 15, que: "Which function is used to parse JSON strings?", opt_1: "JSON.parse()", opt_2: "JSON.stringify()", opt_3: "JSON.convert()", opt_4: "JSON.toString()", ans: "JSON.parse()"},
    {id: 16, que: "What will 'console.log(2 + '2')' output?", opt_1: "22", opt_2: "4", opt_3: "undefined", opt_4: "NaN", ans: "22"},
    {id: 17, que: "Which method is used to remove the last element of an array?", opt_1: "pop()", opt_2: "push()", opt_3: "shift()", opt_4: "unshift()", ans: "pop()"},
    {id: 18, que: "Which keyword is used to define an asynchronous function?", opt_1: "async", opt_2: "await", opt_3: "setTimeout", opt_4: "promise", ans: "async"},
    {id: 19, que: "Which method is used to convert an array to a string?", opt_1: "join()", opt_2: "toString()", opt_3: "Both A and B", opt_4: "concat()", ans: "Both A and B"},
    {id: 20, que: "How can you check if a variable is an array?", opt_1: "Array.isArray()", opt_2: "isArray()", opt_3: "typeof", opt_4: "instanceof", ans: "Array.isArray()"},
    {id: 21, que: "What is the purpose of 'use strict' in JavaScript?", opt_1: "To enforce strict syntax rules", opt_2: "To disable errors", opt_3: "To enable debugging", opt_4: "To define global variables", ans: "To enforce strict syntax rules"},
    {id: 22, que: "Which object is used to handle dates in JavaScript?", opt_1: "Date", opt_2: "Time", opt_3: "Calendar", opt_4: "Clock", ans: "Date"},
    {id: 23, que: "What is a JavaScript Promise?", opt_1: "An object representing the eventual completion of an asynchronous operation", opt_2: "A function that resolves immediately", opt_3: "A way to handle events", opt_4: "A method for data validation", ans: "An object representing the eventual completion of an asynchronous operation"},
    {id: 24, que: "What does the 'this' keyword refer to in JavaScript?", opt_1: "The current object", opt_2: "The global object", opt_3: "The parent object", opt_4: "The current scope", ans: "The current object"},
    {id: 25, que: "Which method is used to add an event listener to an element?", opt_1: "addEventListener()", opt_2: "attachEvent()", opt_3: "onEvent()", opt_4: "setEvent()", ans: "addEventListener()"},
    {id: 26, que: "What is the result of '0 == false' in JavaScript?", opt_1: "true", opt_2: "false", opt_3: "undefined", opt_4: "null", ans: "true"},
    {id: 27, que: "What does 'JSON' stand for?", opt_1: "JavaScript Object Notation", opt_2: "JavaScript Online", opt_3: "Java Serialized Object Notation", opt_4: "JavaScript Output Notation", ans: "JavaScript Object Notation"},
    {id: 28, que: "Which operator is used to spread elements of an array?", opt_1: "...", opt_2: "=>", opt_3: "===", opt_4: "->", ans: "..."},
    {id: 29, que: "What is the correct syntax for a JavaScript arrow function?", opt_1: "() => {}", opt_2: "=> {}", opt_3: "() -> {}", opt_4: "() >> {}", ans: "() => {}"},
    {id: 30, que: "Which statement is used to stop a loop in JavaScript?", opt_1: "break", opt_2: "continue", opt_3: "stop", opt_4: "exit", ans: "break"},
    {id: 31, que: "Which method is used to sort elements of an array?", opt_1: "sort()", opt_2: "order()", opt_3: "arrange()", opt_4: "orderBy()", ans: "sort()"},
    {id: 32, que: "What does 'typeof undefined' return?", opt_1: "undefined", opt_2: "null", opt_3: "object", opt_4: "string", ans: "undefined"},
    {id: 33, que: "Which method is used to reverse an array?", opt_1: "reverse()", opt_2: "invert()", opt_3: "backward()", opt_4: "flip()", ans: "reverse()"},
    {id: 34, que: "What does 'new' keyword do in JavaScript?", opt_1: "Creates a new object", opt_2: "Deletes an object", opt_3: "Initializes a variable", opt_4: "Creates a new array", ans: "Creates a new object"},
    {id: 35, que: "Which JavaScript feature allows writing asynchronous code that looks synchronous?", opt_1: "Async/Await", opt_2: "Promises", opt_3: "Callbacks", opt_4: "Generators", ans: "Async/Await"},
    {id: 36, que: "Which loop structure is used to iterate over the properties of an object?", opt_1: "for...in", opt_2: "for...of", opt_3: "while", opt_4: "do...while", ans: "for...in"},
    {id: 37, que: "Which JavaScript method is used to delay execution of a function?", opt_1: "setTimeout()", opt_2: "setInterval()", opt_3: "delay()", opt_4: "wait()", ans: "setTimeout()"},
    {id: 38, que: "Which object method can be used to create a shallow copy of an object?", opt_1: "Object.assign()", opt_2: "Object.copy()", opt_3: "Object.clone()", opt_4: "Object.duplicate()", ans: "Object.assign()"},
    {id: 39, que: "What will be the output of 'console.log(typeof NaN)'?", opt_1: "number", opt_2: "NaN", opt_3: "undefined", opt_4: "object", ans: "number"},
    {id: 40, que: "Which method is used to combine two or more arrays?", opt_1: "concat()", opt_2: "merge()", opt_3: "combine()", opt_4: "append()", ans: "concat()"},
    {id: 41, que: "What does the 'finally' block do in a try-catch-finally statement?", opt_1: "Executes code after try and catch regardless of the outcome", opt_2: "Handles exceptions", opt_3: "Skips the catch block", opt_4: "Defines a function", ans: "Executes code after try and catch regardless of the outcome"},
    {id: 42, que: "What will 'console.log(1 + true)' output?", opt_1: "2", opt_2: "true1", opt_3: "NaN", opt_4: "undefined", ans: "2"},
    {id: 43, que: "Which keyword is used to declare a constant in JavaScript?", opt_1: "const", opt_2: "var", opt_3: "let", opt_4: "constant", ans: "const"},
    {id: 44, que: "What does the 'Promise.all()' method do?", opt_1: "Waits for all promises to resolve", opt_2: "Executes promises sequentially", opt_3: "Rejects immediately if one promise rejects", opt_4: "Both A and C", ans: "Both A and C"},
    {id: 45, que: "What is the difference between '==' and '===' in JavaScript?", opt_1: "'==' compares value only, '===' compares value and type", opt_2: "Both compare value and type", opt_3: "'==' is faster", opt_4: "'===' is used for strings only", ans: "'==' compares value only, '===' compares value and type"},
    {id: 46, que: "Which statement is true about 'let' and 'var'?", opt_1: "'let' has block scope, 'var' has function scope", opt_2: "'let' and 'var' are identical", opt_3: "'var' is faster than 'let'", opt_4: "'let' cannot be reassigned", ans: "'let' has block scope, 'var' has function scope"},
    {id: 47, que: "What is the purpose of 'Array.prototype.map()'?", opt_1: "To create a new array with the results of calling a function on every element", opt_2: "To filter array elements", opt_3: "To reverse array elements", opt_4: "To sort array elements", ans: "To create a new array with the results of calling a function on every element"},
    {id: 48, que: "Which method is used to check if a string contains a specific value?", opt_1: "includes()", opt_2: "contains()", opt_3: "hasValue()", opt_4: "search()", ans: "includes()"},
    {id: 49, que: "What is the output of 'console.log(typeof [])'?", opt_1: "object", opt_2: "array", opt_3: "undefined", opt_4: "function", ans: "object"},
    {id: 50, que: "Which method is used to round a number to the nearest integer?", opt_1: "Math.round()", opt_2: "Math.ceil()", opt_3: "Math.floor()", opt_4: "Math.abs()", ans: "Math.round()"}
]     
};

const questions_2 = {
    html: [
        {id: 1, que: "What does HTML stand for?", opt_1: "Hyper Text Markup Language", opt_2: "Hyperlinks and Text Markup Language", opt_3: "Home Tool Markup Language", opt_4: "Hyper Text Manipulation Language", ans: "Hyper Text Markup Language"},
        {id: 2, que: "Who is the father of HTML?", opt_1: "Tim Berners-Lee", opt_2: "Dennis Ritchie", opt_3: "James Gosling", opt_4: "Guido van Rossum", ans: "Tim Berners-Lee"},
        {id: 3, que: "Which tag is used for the largest heading?", opt_1: "<h1>", opt_2: "<h6>", opt_3: "<header>", opt_4: "<head>", ans: "<h1>"},
        {id: 4, que: "Which tag is used to create a hyperlink?", opt_1: "<a>", opt_2: "<link>", opt_3: "<href>", opt_4: "<anchor>", ans: "<a>"},
        {id: 5, que: "Which attribute is used to provide a unique identifier in HTML?", opt_1: "id", opt_2: "class", opt_3: "name", opt_4: "key", ans: "id"},
        {id: 6, que: "Which HTML tag is used to define an unordered list?", opt_1: "<ul>", opt_2: "<ol>", opt_3: "<li>", opt_4: "<list>", ans: "<ul>"},
        {id: 7, que: "Which tag is used to insert an image in HTML?", opt_1: "<img>", opt_2: "<image>", opt_3: "<src>", opt_4: "<picture>", ans: "<img>"},
        {id: 8, que: "What is the correct HTML tag for inserting a line break?", opt_1: "<br>", opt_2: "<break>", opt_3: "<lb>", opt_4: "<line>", ans: "<br>"},
        {id: 9, que: "Which tag is used to create a dropdown list in HTML?", opt_1: "<select>", opt_2: "<dropdown>", opt_3: "<option>", opt_4: "<list>", ans: "<select>"},
        {id: 10, que: "What is the purpose of the <title> tag in HTML?", opt_1: "Defines the document's title in the browser's tab", opt_2: "Displays a heading", opt_3: "Links to an external CSS file", opt_4: "Creates a hyperlink", ans: "Defines the document's title in the browser's tab"},
        {id: 11, que: "What does the <meta> tag provide in HTML?", opt_1: "Metadata about the document", opt_2: "Defines document structure", opt_3: "Embeds an image", opt_4: "Creates a table", ans: "Metadata about the document"},
        {id: 12, que: "Which tag is used to display a table in HTML?", opt_1: "<table>", opt_2: "<tab>", opt_3: "<row>", opt_4: "<data>", ans: "<table>"},
        {id: 13, que: "How can you make text bold in HTML?", opt_1: "<b>", opt_2: "<bold>", opt_3: "<strong>", opt_4: "<em>", ans: "<b>"},
        {id: 14, que: "Which tag is used to play audio in HTML?", opt_1: "<audio>", opt_2: "<sound>", opt_3: "<media>", opt_4: "<music>", ans: "<audio>"},
        {id: 15, que: "What does the <iframe> tag do?", opt_1: "Embeds another document within the current document", opt_2: "Displays an image", opt_3: "Defines an inline style", opt_4: "Creates a form", ans: "Embeds another document within the current document"},
        {id: 16, que: "Which tag is used to create a checkbox in HTML?", opt_1: "<input type='checkbox'>", opt_2: "<checkbox>", opt_3: "<input type='check'>", opt_4: "<option>", ans: "<input type='checkbox'>"},
        {id: 17, que: "Which HTML attribute specifies an alternate text for an image?", opt_1: "alt", opt_2: "src", opt_3: "title", opt_4: "name", ans: "alt"},
        {id: 18, que: "What is the default alignment of text in an HTML document?", opt_1: "Left", opt_2: "Center", opt_3: "Right", opt_4: "Justify", ans: "Left"},
        {id: 19, que: "Which doctype declaration is correct for HTML5?", opt_1: "<!DOCTYPE html>", opt_2: "<DOCTYPE HTML5>", opt_3: "<DOCTYPE html5>", opt_4: "<DOCTYPE>", ans: "<!DOCTYPE html>"},
        {id: 20, que: "Which attribute is used to open a link in a new tab?", opt_1: "target='_blank'", opt_2: "target='_new'", opt_3: "rel='newtab'", opt_4: "rel='_blank'", ans: "target='_blank'"}
    ],

    css: [
        {id: 1, que: "What does CSS stand for?", opt_1: "Cascading Style Sheets", opt_2: "Creative Style Sheets", opt_3: "Computer Style Sheets", opt_4: "Colorful Style Sheets", ans: "Cascading Style Sheets"},
        {id: 2, que: "Which property is used to change the background color?", opt_1: "background-color", opt_2: "color", opt_3: "bgcolor", opt_4: "background", ans: "background-color"},
        {id: 3, que: "How do you make text bold in CSS?", opt_1: "font-weight: bold;", opt_2: "font-style: bold;", opt_3: "text-weight: bold;", opt_4: "style: bold;", ans: "font-weight: bold;"},
        {id: 4, que: "Which property is used to change the font size?", opt_1: "font-size", opt_2: "text-size", opt_3: "font-style", opt_4: "size", ans: "font-size"},
        {id: 5, que: "How do you apply a CSS class to an element?", opt_1: "class='classname'", opt_2: "id='classname'", opt_3: "name='classname'", opt_4: "tag='classname'", ans: "class='classname'"},
        {id: 6, que: "Which property is used to set the text color?", opt_1: "color", opt_2: "text-color", opt_3: "font-color", opt_4: "background-color", ans: "color"},
        {id: 7, que: "Which property is used to align text to the center?", opt_1: "text-align: center;", opt_2: "align: center;", opt_3: "vertical-align: center;", opt_4: "justify: center;", ans: "text-align: center;"},
        {id: 8, que: "Which property is used to add a shadow to text?", opt_1: "text-shadow", opt_2: "font-shadow", opt_3: "shadow", opt_4: "text-outline", ans: "text-shadow"},
        {id: 9, que: "How do you make a list with no bullet points?", opt_1: "list-style-type: none;", opt_2: "text-decoration: none;", opt_3: "list-type: none;", opt_4: "bullet: none;", ans: "list-style-type: none;"},
        {id: 10, que: "What is the default position value in CSS?", opt_1: "static", opt_2: "relative", opt_3: "absolute", opt_4: "fixed", ans: "static"},
        {id: 11, que: "Which property is used to add space inside an element's border?", opt_1: "padding", opt_2: "margin", opt_3: "border-spacing", opt_4: "spacing", ans: "padding"},
        {id: 12, que: "Which property is used to add space outside an element?", opt_1: "margin", opt_2: "padding", opt_3: "border-spacing", opt_4: "spacing", ans: "margin"},
        {id: 13, que: "Which property controls the order of layers in overlapping elements?", opt_1: "z-index", opt_2: "layer-order", opt_3: "position", opt_4: "display", ans: "z-index"},
        {id: 14, que: "How do you make an element disappear but still occupy space?", opt_1: "visibility: hidden;", opt_2: "display: none;", opt_3: "opacity: 0;", opt_4: "hidden: true;", ans: "visibility: hidden;"},
        {id: 15, que: "Which property is used to create rounded corners?", opt_1: "border-radius", opt_2: "corner-radius", opt_3: "border-corner", opt_4: "radius", ans: "border-radius"},
        {id: 16, que: "Which property is used to set the maximum width of an element?", opt_1: "max-width", opt_2: "width", opt_3: "min-width", opt_4: "height", ans: "max-width"},
        {id: 17, que: "Which unit is relative to the font size of the root element?", opt_1: "rem", opt_2: "em", opt_3: "px", opt_4: "%", ans: "rem"},
        {id: 18, que: "How can you include an external CSS file in an HTML document?", opt_1: "<link rel='stylesheet' href='styles.css'>", opt_2: "<style src='styles.css'>", opt_3: "<script src='styles.css'>", opt_4: "<stylesheet href='styles.css'>", ans: "<link rel='stylesheet' href='styles.css'>"},
        {id: 19, que: "Which property is used to change the cursor icon?", opt_1: "cursor", opt_2: "pointer", opt_3: "icon", opt_4: "hover", ans: "cursor"},
        {id: 20, que: "What does the 'float' property do?", opt_1: "Positions an element to the left or right of its container", opt_2: "Centers an element", opt_3: "Adds space between elements", opt_4: "Makes an element scrollable", ans: "Positions an element to the left or right of its container"}
    ],

    js: [
        {id: 1, que: "What does JavaScript primarily run on?", opt_1: "Browser", opt_2: "Server", opt_3: "Operating System", opt_4: "Hardware", ans: "Browser"},
        {id: 2, que: "Which keyword is used to declare a variable in JavaScript?", opt_1: "var", opt_2: "let", opt_3: "const", opt_4: "All of the above", ans: "All of the above"},
        {id: 3, que: "What does 'typeof null' return?", opt_1: "object", opt_2: "null", opt_3: "undefined", opt_4: "number", ans: "object"},
        {id: 4, que: "Which symbol is used for comments in JavaScript?", opt_1: "//", opt_2: "/* */", opt_3: "#", opt_4: "Both // and /* */", ans: "Both // and /* */"},
        {id: 5, que: "How can you convert a string to a number in JavaScript?", opt_1: "Number()", opt_2: "parseInt()", opt_3: "parseFloat()", opt_4: "All of the above", ans: "All of the above"},
        {id: 6, que: "Which method is used to add an element to an array?", opt_1: "push()", opt_2: "add()", opt_3: "append()", opt_4: "insert()", ans: "push()"},
        {id: 7, que: "What will the following code output: console.log(2 + '2');?", opt_1: "'22'", opt_2: "4", opt_3: "Error", opt_4: "undefined", ans: "'22'"},
        {id: 8, que: "What is the correct syntax for a function in JavaScript?", opt_1: "function myFunc() {}", opt_2: "function = myFunc() {}", opt_3: "def myFunc() {}", opt_4: "func myFunc() {}", ans: "function myFunc() {}"},
        {id: 9, que: "How do you call a function named 'myFunction'?", opt_1: "myFunction()", opt_2: "call myFunction", opt_3: "myFunction[]", opt_4: "call function myFunction", ans: "myFunction()"},
        {id: 10, que: "Which event occurs when a user clicks on an HTML element?", opt_1: "onclick", opt_2: "onmouseover", opt_3: "onchange", opt_4: "onpress", ans: "onclick"},
        {id: 11, que: "Which operator is used to assign a value to a variable?", opt_1: "=", opt_2: "==", opt_3: "===", opt_4: "=>", ans: "="},
        {id: 12, que: "What does the '===' operator do in JavaScript?", opt_1: "Checks both value and type", opt_2: "Checks only value", opt_3: "Checks only type", opt_4: "Assigns a value", ans: "Checks both value and type"},
        {id: 13, que: "Which object in JavaScript is the root object?", opt_1: "Window", opt_2: "Document", opt_3: "Global", opt_4: "Parent", ans: "Window"},
        {id: 14, que: "Which method is used to join two arrays?", opt_1: "concat()", opt_2: "join()", opt_3: "merge()", opt_4: "append()", ans: "concat()"},
        {id: 15, que: "Which keyword is used to define an asynchronous function?", opt_1: "async", opt_2: "await", opt_3: "asynchronous", opt_4: "promise", ans: "async"},
        {id: 16, que: "What will the following code output: console.log(typeof NaN);?", opt_1: "number", opt_2: "NaN", opt_3: "undefined", opt_4: "string", ans: "number"},
        {id: 17, que: "How do you check if an object has a specific property?", opt_1: "'property' in object", opt_2: "object.has(property)", opt_3: "object[property] != undefined", opt_4: "object.includes(property)", ans: "'property' in object"},
        {id: 18, que: "How do you create an object in JavaScript?", opt_1: "{}", opt_2: "new Object()", opt_3: "Both {} and new Object()", opt_4: "object()", ans: "Both {} and new Object()"},
        {id: 19, que: "Which function is used to iterate over an array?", opt_1: "forEach()", opt_2: "map()", opt_3: "filter()", opt_4: "All of the above", ans: "All of the above"},
        {id: 20, que: "What does 'use strict' do in JavaScript?", opt_1: "Enforces strict mode for better error handling", opt_2: "Ignores type checking", opt_3: "Prevents errors from being thrown", opt_4: "Optimizes code execution", ans: "Enforces strict mode for better error handling"}
    ]  
};

const questions_template = {
    html: [
        {id: 1, que: "HTML Question 1?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 1"},
        {id: 2, que: "HTML Question 2?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 2"},
        {id: 3, que: "HTML Question 3?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 3"},
        {id: 4, que: "HTML Question 4?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 4"},
    ],
    css: [
        {id: 1, que: "CSS Question 1?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 1"},
        {id: 2, que: "CSS Question 2?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 2"},
        {id: 3, que: "CSS Question 3?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 3"},
        {id: 4, que: "CSS Question 4?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 4"},
    ],
    js: [
        {id: 1, que: "JS Question 1?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 1"},
        {id: 2, que: "JS Question 2?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 2"},
        {id: 3, que: "JS Question 3?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 3"},
        {id: 4, que: "JS Question 4?", opt_1: "Option 1", opt_2: "Option 2", opt_3: "Option 3", opt_4: "Option 4", ans: "Option 4"},
    ]
};
